use TRACS_CUSTOM;
CREATE TABLE dbo.PCORNET_FHIR_MAPPING  ( 
	TABLE_CD       	VARCHAR(50) NULL,
	COLUMN_CD      	VARCHAR(50) NULL,
	LOCAL_IN_CD    	VARCHAR(50) NULL,
	FHIR_OUT_CD    	VARCHAR(50) NULL,
	FHIR_OUT_CHAR  	VARCHAR(100) NULL,
	COMMENTS       	VARCHAR(200) NULL,
	FHIR_OUT_COLUMN	VARCHAR(50) NULL,
	FHIR_SYSTEM    	VARCHAR(200) NULL 
	)
  
  
